### ISSUE TITLE
Add support for Magic Castle 8

### ISSUE THREAD

**Issue by lefreud** [ComputeCanada/magic_castle-ui#10]
[Magic Castle 8](https://github.com/ComputeCanada/magic_castle/releases/tag/8.0) requires an SSH agent configured with the cluster's private key to upload files to the instances via SSH.

**Comment by cmd-ntrf** [comment]
Try this PR which implements the ssh key generation in MC:
https://github.com/ComputeCanada/magic_castle/pull/96

**Comment by lefreud** [comment]
Thanks! It should work perfectly with MC-UI.

I will update the release of Magic Castle used in MC-UI when you officially release version 8.1.
